README.markdown, build.d
In the current procedure in `README.markdown` will fail to build on Linux Mint 17.1(64bit).
Accordingly, I added the procedure to README.
And since link errors has occurred, I fixed `build.d`.
=> Succeeded to build on Linux Mint 17.1(64-bit).

org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/internal/image/JPEGDecoder.d
https://issues.dlang.org/show_bug.cgi?id=19758
This problem occurs in the DWT's JPEG decoder. As a result, a JPEG image is broken on Windows 64-bit.
If assign a value of htbl.bits into a variable, We can avoid generating wrong code.
This is a problem to be solved by the dmd fix. I can't tell if this code should be merged.
=> Workaround: https://issues.dlang.org/show_bug.cgi?id=19758

org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/ole/win32/OleClientSite.d, org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/ole/win32/OleControlSite.d
A compilation error:
org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\ole\win32\OleControlSite.d(886,43): Error: class `org.eclipse.swt.ole.win32.OleControlSite.OleControlSite` member AddRef is not accessible
org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\ole\win32\OleControlSite.d(906,43): Error: class `org.eclipse.swt.ole.win32.OleControlSite.OleControlSite` member AddRef is not accessible
=> Fixes for dmd 2.087.0.

org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/widgets/Synchronizer.d, org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/widgets/Synchronizer.d
See Also: issue #49, pull request #50
A semaphore handles was not closed when a exception occurred.
Use a scope guard statement to ensure that handles is closed.
=> Close a handles even if an exception occurs.

org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/internal/c/gtk.d, org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/internal/gtk/OS.d, org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/program/Program.d, org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/widgets/Table.d
Rewrited a functions that can't be used due to the GTK specification change, I has been successfully ran all snippets with minimal changes.
There are some parts where we do not know if we need to take fix. e.g. `GTK_WIDGET_SET_FLAGS(widget, GTK_HAS_FOCUS)`. However, it works without problems in the range I tried.
By the way, fixed that some pointers were handled as int.
=> Compatible the specification change of GTK 2.20.0 and 2.22.0

org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/widgets/Shell.d
https://github.com/d-widget-toolkit/dwt/issues/34#issuecomment-600725811
It seemed to be "a" long ago. For reference, current swt code:
OS.gtk_window_set_title (shellHandle, new byte [1]);
=> Change default shell title from "a" to "".

base/src/java/lang/util.d, org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/internal/c/glx.d, org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/internal/c/gtk.d
Fixes for dmd 2.092.0.
Module constructors must be extern(D).
I fixed static this() where linkage is extern(C) or extern(Windows).
=> A module constructors must be extern(D).

dub.sdl, org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/SnippetPaintItem.d, org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/widgets/Table.d, org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/widgets/TableColumn.d, org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/widgets/Tree.d
I found a bugs when I used the `Table` custom drawing.
* A 8-bit value returned by SendMessage(64) is compared to `OS.CLR_NONE`(0xffffffff) without conversion to `COLOREF`(4-bit). I had same problem with `Tree`, so I fixed it.
* There was still a part where a pointer which is LPARAM was cast to int.
And a table header were not shown with Windows 32-bit build. Need a linker flag of Windows Subsystem.
=> Custom drawing of Table is broken on Windows 64-bit.

dub.sdl
Because LDC uses Microsoft's linker, the flags for OPTLINK cause problems.
=> Build fails with LDC(x86) on Windows.

org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/internal/win32/WINTYPES.d
https://dlang.org/changelog/2.095.0.html#duplicate-implementations-deprecation
Since these functions are prepared to reproduce bitfields, there is no problem in changing a calling convention.
For example, the following C structure:
```C
typedef struct tag_SCRIPT_ANALYSIS {
WORD         eScript : 10;
WORD         fRTL : 1;
WORD         fLayoutRTL : 1;
WORD         fLinkBefore : 1;
WORD         fLinkAfter : 1;
WORD         fLogicalOrder : 1;
WORD         fNoGlyphIndex : 1;
SCRIPT_STATE s;
} SCRIPT_ANALYSIS;
```
This structure is reproduced as follows:
```D
struct SCRIPT_ANALYSIS {
WORD BITS;
SCRIPT_STATE s;
extern(D):
// getter
uint eScript()      { return BITS & 0x03FFU; }
uint fRTL()         { return btvg(&BITS, 10); }
uint fLayoutRTL()   { return btvg(&BITS, 11); }
uint fLinkBefore()  { …
```
=> A functions with same name are declared with extern(D).

org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/custom/StyledText.d, org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/graphics/Device.d, org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/graphics/GC.d, org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/graphics/ImageLoader.d, org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/graphics/Path.d, org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/graphics/Transform.d, org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/internal/image/PNGFileFormat.d, org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/internal/image/PngEncoder.d
These methods were deprecated by changes in the Compatibility class (commit 14f801a).  Only one not updated is in Synchronizer.d, which would throw an "Implementation Missing" exception because Thread.interrupt hasn't been implemented.
I would like to send a separate pull request to implement the interrupt method, but I'm not completely sure how to.
=> [Gtk] Fix usage of deprecated methods.

tests/Platform.d
I came across an error I made when moving the Platform unit tests to the separate file.  I'm sorry, but here's a fix.
=> [unittest] Fix Platform imports

base/src/java/nonstandard/SafeUtf.d, base/src/java/nonstandard/UtfBase.d
Fixes the SafeUtf unittests.
As I wrote in the commit message, an `opEquals` overload was added to the `UTF8shift` struct and a separation between the `foreach` iterator and the actual `UTF8index` was made.
=> [base] Fix SafeUtf unittests

org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/graphics/RGB.d, tests/RGB.d
Nothing really different, but the `const` is needed for `getHSB` so it can be used in the `RGBA` class (for which, I'll send a pull request after this).
Also added the unit tests.
=> [Gtk] Update RGB to 4.7.3

org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/graphics/RGBA.d, tests/RGBA.d
As you'd expect, it's mostly the same as the `RGB` class, just with the addition of alpha.
After this, I'll work on fixing the current issues preventing the CI from passing the tests.
=> [Gtk] Add RGBA class

base/src/java/util/HashSet.d
Fixes the `HashSet#add` method so the base library can compile on D versions < 2.092.
=> [base] Fix support for D versions < 2.092

.gitignore, base/src/java/lang/util.d
This PR fixes the failing unittest in [java/lang/util.d#L322 ](https://github.com/d-widget-toolkit/dwt/blob/56cc788107b7e8626d8b460fd97078c626e97142/base/src/java/lang/util.d#L332) and makes some adjustments to allow formatting of arrays.
The code is mostly just a copy of the existing `fmtFromTangoFmt` function, with the difference being the changes to support arrays and to allows for a mix between positional and non-positional formatting (e.g. `{} {1} {}`) .
I've marked this as a draft as I haven't removed the `fmtFromTangoFmt` code (and fixed references) since I wanted to see if you had another way to go about this.
=> [base] Allow Format to apply format to array

org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet1.d, org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet10.d, org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet2.d, org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet3.d, org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet4.d, org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet5.d, org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet6.d, org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet7.d, org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet8.d, org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet9.d
I noticed there are some non-translated snippets.  This pull request adds snippets 1 - 6, and updates 7 - 10.
I tested these on a Windows VM as well and they worked, though the x86 VM required `--arch=x86`. Judging from issue #61 and the release notes of [dub 1.23], it's probably the same issue.
[dub 1.23]: https://github.com/dlang/dub/releases/tag/v1.23.0
=> Update snippets 1 - 10

org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/internal/Converter.d
This also fixes an issue where LDC would fail to compile due to a function signature mismatch with the g_utf16_to_utf8 declared in the OS module (an alias to glib_object.d).  I left them declared in Converter.d since they require less casts.
=> Update Converter.d to 4.7.3

org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/graphics/Color.d, org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/graphics/all.d, org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/internal/gtk/OS.d, tests/Color.d
Updates the Gtk `Color` class to match SWT version 4.7.3.
I also missed adding an `import` to the `graphics.all` module for the `RGBA` class when that was originally added, so I've included it here.
=> [Gtk] Update Color.d to 4.7.3

org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/graphics/RGB.d
Will allow the addition of the `RGBA` class on Windows (`getHSB` needs `const`).
=> [win32] Update RGB.d to 4.7.3

base/src/java/util/zip/DeflaterOutputStream.d
`java.io.OutputStream.OutputStream` was used a few times without any importing but it worked due to [DMD bug](https://github.com/dlang/dmd/pull/12215).
=> Import 'java.io.OutputStream.OutputStream' properly

org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/widgets/Text.d
VerifyEvent.character is wchar, but since it is cast to char, a result will be wrong when handling a multibyte character.
For example, the character `」` will be misrecognized as a `\r\n`.
=> Wrong handling of a multibyte character in VerifyEvent.

org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/custom/StyleRange.d, org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/graphics/Font.d, org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/graphics/GlyphMetrics.d, org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/graphics/TextStyle.d
This will allow the AccessibleEditableText* classes to implement a const toString() function.
I'll send a pull request adding the AccessibleEditableText classes, if this one is okay.
=> [Gtk] Add const attribute to some member functions

org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/accessibility/AccessibleActionAdapter.d, org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/accessibility/AccessibleActionEvent.d, org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/accessibility/AccessibleActionListener.d, org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/accessibility/all.d, org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/accessibility/AccessibleActionAdapter.d, org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/accessibility/AccessibleActionEvent.d, org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/accessibility/AccessibleActionListener.d, org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/accessibility/all.d
Add the AccessibleActionAdapter, AccessibleActionEvent, and AccessibleActionListener classes.
Since these are a part of the "common" directory in SWT — and there is nothing platform specific here — did you want me to add the classes for the Windows version in this pull request?
=> Add AccessibleAction* classes

org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/custom/StyleRange.d, org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/graphics/Color.d, org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/graphics/Font.d, org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/graphics/GlyphMetrics.d, org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/graphics/TextStyle.d
Probably should have included these in #82, since it's for the same reason.
There is a difference between this pull request and the last, which is the changes in the `Color` class. That's because the Gtk `Color` has been updated to 4.7.3 (`const` was added then, see #75) but the win32 version has not been updated.
=> Add const to some win32 member functions

org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/accessibility/AccessibleTextAttributeEvent.d, org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/accessibility/all.d, org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/accessibility/AccessibleTextAttributeEvent.d, org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/accessibility/all.d
This translates the Java version of the `AccessibleTextAtrributeEvent` class to D.
The code is the same for both the win32 and Gtk versions.
=> Add AccessibleTextAtrributeEvent class

org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/accessibility/AccessibleActionEvent.d, org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/accessibility/AccessibleAdapter.d, org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/accessibility/AccessibleControlAdapter.d, org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/accessibility/AccessibleControlEvent.d, org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/accessibility/AccessibleControlListener.d, org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/accessibility/AccessibleEvent.d, org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/accessibility/AccessibleTextAdapter.d, org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/accessibility/AccessibleTextAttributeEvent.d, org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/accessibility/AccessibleTextEvent.d, org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/accessibility/AccessibleTextListener.d, org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/accessibility/AccessibleActionEvent.d, org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/accessibility/AccessibleAdapter.d, org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/accessibility/AccessibleControlAdapter.d, org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/accessibility/AccessibleControlEvent.d, org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/accessibility/AccessibleControlListener.d, org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/accessibility/AccessibleEvent.d, org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/accessibility/AccessibleTextAdapter.d, org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/accessibility/AccessibleTextAttributeEvent.d, org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/accessibility/AccessibleTextEvent.d, org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/accessibility/AccessibleTextListener.d
This updates the pre-existing accessibility classes to the equivalent of SWT 4.7.3.
Mostly just comments but there are some code changes, nothing that should cause breakage though.
=> Update Accessibility classes to 4.7.3

org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/graphics/PaletteData.d, org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/graphics/PaletteData.d, tests/PaletteData.d
This will update the `PaletteData` class to SWT version 4.7.3.  Nothing major, but the `shiftForMask` method has been given the `package` visibility.
New unittests are also included.
=> Update PaletteData class.

.github/workflows/ci.yml, dub.sdl, org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/widgets/Display.d
Error was thrown when trying to build (using dub) with `-b release`. Not sure what the plan for `p` was, as SWT doesn't actually set an error handler for X in the Display class.
=> [gtk] Fix null dereference in Display

org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/graphics/Device.d, org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/graphics/Drawable.d, org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/graphics/Image.d, org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/printing/Printer.d, org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/widgets/Control.d, org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/graphics/Device.d, org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/graphics/Drawable.d, org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/graphics/Image.d, org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/printing/Printer.d, org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/widgets/Control.d
Updates the `Drawable` interface to match what SWT 4.7.3 has.
SWT uses the `default` keyword so implement a default function body. As D doesn't have an equivalent, I just implemented the default function body in any class which directly implements the `Drawable` interface.
The `Printer` class has a non-default function body, which has been used.
=> Update Drawable to 4.7.3

org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/ImageDataProvider.d
This ports the `ImageDataProvider` interface from SWT 4.7.3.
This interface is implemented by a class that I'm currently porting, so here it is now.
=> Port ImageDataProvider 4.7.3

.github/workflows/ci.yml
Small change to have to CI run when pull requests target the `4.7` branch.
I have this targeting the `4.7` branch since, [according to the docs](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#example-using-multiple-events-with-activity-types-or-configuration):
> The following steps occur to trigger a workflow run:
> [...]
> 2. The `.github/workflows` directory in your repository is searched for workflow files at the associated commit SHA or Git ref. The workflow files must be present in that commit SHA or Git ref to be considered.
>
> For example, if the event occurred on a particular repository branch, then the workflow files must be present in the repository on that branch.
If you want it to target the `master` branch, just let me know.
=> Run CI on pull requests for branch 4.7

org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/DPIUtil.d
This pull request starts the process of porting the `DPIUtil` class from SWT 4.7.3.
It's not complete yet, as one of the methods requires a new constructor for the `Image` class (which I'll add in a separate pull request). However, that constructor requires the methods that I've currently ported in the `DPIUtil` class -- hence why this is the pull request I'm sending first.
=> Start port of DPIUtil

base/src/java/lang/exceptions.d
This adds the `ClassNotFoundException` class.
As sort of mentioned in #103, when trying to implement a new constructor for the `Image` class, I encountered a cyclic dependency error.
I have a local fix complete, this is just the beginning of it.
This also drops support for Tango in the file.
=> Add ClassNotFoundException

org.eclipse.swt.win32.win32.x86/src/org/eclipse/swt/widgets/Text.d
Error "surrogate UTF-16 high value past end of string" when trying to enter a 32-bit Emoji in a Text control that listen VerifyEvent.
For Windows' convenience, processing is done in units of wchar, so dchar will be split into two incomplete wchars when processing VerifyEvent. Using to!string for incomplete characters will result in an error.
=> Error when trying to enter a 32-bit Emoji in a Text control that listen VerifyEvent.

base/src/java/nonstandard/UtfBase.d
Soon, backslashes will need escaping in the file spec of `#line` directives.
=> java.nonstandard.UtfBase: Use forward slashes in #line sequence

base/src/java/nonstandard/UtfBase.d
I tested this little change first on Neon 22.04 on x86_64 under QEMU/KVM.
The current actions seem to pass okay, but I'm kinda new to that.
Much respect on this project.  To me it's a gateway to D from java.
Glad to help wherever if you want to ping me direct daniel.pflager@gmail.com
=> changing to forward slashes makes linux neon happy
